### ISSUE TITLE
0% GPU usage (version 0.7.0)

### ISSUE THREAD

**Issue by jsteggink** [deeplearning4j/deeplearning4j#2355]
With the exact same model on version 0.6.0 I have good usage of GPU (30-50%). 
However, on version 0.7.0 it's zero usage. I'm using mini batch sizes of 1000.

I'm on Windows btw.

[configuration.zip](https://github.com/deeplearning4j/deeplearning4j/files/607121/configuration.zip)

**Comment by raver119** [comment]
Can you please run LenetMnistExample on 0.6.0 and 0.7.0, and instead of reporting gpu utilization, use PerformanceListener?

**Comment by jsteggink** [comment]
Sure, no problem.

**Comment by raver119** [comment]
Also, please provide us with gist of your configuration as java code.

**Comment by jsteggink** [comment]
Ok, I found the problem. It has nothing to do with the neural nets. It's the DataSetIterator.
I have a lookup table my custom DataSetIterator. but for the fun of it, just add a big object to a random DataSetIterator:
`Object[] objects = new Object[500000000];`

https://gist.github.com/jsteggink/9650dad58f492e913daf351eb5960f0e

When I check VisualVM, I see this:
![jvisualvm](https://cloud.githubusercontent.com/assets/978411/20560561/4a2fe6ea-b17a-11e6-900e-e93d99398317.png)

**Comment by raver119** [comment]
I don't get you here. You've added array of Object, 500m elements. You show profiler screenshot with 2GB ram used. What's the point?

**Comment by agibsonccc** [comment]
I don't get the object array, but he's saying the bottleneck is his iterator. Beyond hat not sure :D

**Comment by jsteggink** [comment]
Ah sorry about that. The point is that without the array of Object it's all super fast. With it, it's suuuper slow. Just try and see. I noticed there was a difference between version 0.6.0 and 0.7.0. With 0.7.0 it's way slower. But worries me the most is that it has an impact on speed of the network.

**Comment by raver119** [comment]
Well, you've got 2GB of ram in heap. Probably your xmx value is close enough to bottom, so it's just causing excessive GC activity.

In other words: check out all other tabs in profiler :)

**Comment by jsteggink** [comment]
![jvisualvm2](https://cloud.githubusercontent.com/assets/978411/20562755/8bf3eddc-b185-11e6-9e4b-e4b85be3a7ea.png)
![jvisualvm3](https://cloud.githubusercontent.com/assets/978411/20562756/8bf82082-b185-11e6-9c22-624b57185c20.png)

**Comment by raver119** [comment]
Allow higher Xmx.

**Comment by treo** [comment]
The point here is that nd4j respects your -Xmx value, even if it is offheap, so what you are seeing is that due to overall memory pressure GC has to run more often.

**Comment by jsteggink** [comment]
I have increased the heap to 12G, however this does not change the slowness.

See the difference below:

No Object array:
20.794529242592542
o.d.o.listeners.PerformanceListener - iteration 1; iteration time: 629 ms; samples/sec: 1589,825; batches/sec: 1,590;
With Object array:
o.d.o.listeners.PerformanceListener - iteration 1; iteration time: 51488 ms; samples/sec: 19,422; batches/sec: 0,019;

It might help for someone to just try it and see what happens, if you haven't already.

**Comment by raver119** [comment]
Thanks, I'll investigate this.

23 нояб. 2016 г. 16:41 пользователь "jsteggink" <notifications@github.com>
написал:

**Comment by lpaatero** [comment]
I am seeing this same problem in 0.7.0.
I have two computing tasks, that are fast, if run independently:
1) task that generates lots of relatively short living garbage 
2) CUDA optimization
Running these two tasks parallel in same JVM creates this situation. Increasing -Xmx does not impact problem.

**Comment by raver119** [comment]
@lpaatero mind adding some more details about your issue?

**Comment by raver119** [comment]
@lpaatero Especially about that "relatively short living garbage". Is that strict JVM objects, or it's INDArrays or anything else from DL4j/ND4j/DataVec environment?

**Comment by lpaatero** [comment]
Garbage is plain Java objects.

I attempted to create small test when looking at this. It fails to some extent, but not as badly as real system. Simulation has gargabeSimulation linked list for (artifical) garbage, and removal delay allows experimenting with garbage lifetime.

[simulation.zip](https://github.com/deeplearning4j/deeplearning4j/files/617493/simulation.zip)

**Comment by raver119** [comment]
Have you tried using different GCs?

**Comment by raver119** [comment]
Also, what JVM you're running? Tell me vendor and version please.

**Comment by lpaatero** [comment]
hmm, interesting I was running java 9 (I believed to be at 8). 
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-26-230040.abuild.jdk9-55b6d550828d)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-26-230040.abuild.jdk9-55b6d550828d, mixed mode)
Running in Opensuse tumbleweed.
(I will anyway switch back to 8 about now.)

**Comment by raver119** [comment]
Please try if it's reproducible on java8 for you, and check different GCs as well. Basically G1/ConcMarkSweep difference is kind of interest here.

**Comment by lpaatero** [comment]
Problem is present in java8 in the same way. Also it seems to be the same with both G1 and ConcMarkSweep.
Java version is
```
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (IcedTea 3.2.0) (suse-1.1-x86_64)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)

```
And to better simulate the problem, just change garbage generation to
```
// simulate garbage 
    gargabeSimulation.addLast(new int[500000][10]);
    if (gargabeSimulation.size()>3)
      gargabeSimulation.removeFirst();
```

**Comment by raver119** [comment]
So, to reproduce this issue, i've modified LenetMnistExample, by adding few lines of code:

```
Thread thread = new Thread(new Runnable() {
            Deque<int[][]> queue = new ArrayDeque<>();
            @Override
            public void run() {
                while (true) {
                    queue.add(new int[50000][100]);
                    if (queue.size() > 10)
                        queue.removeFirst();
                }
            }
        });

        thread.setDaemon(true);
        thread.start();
```

This particular code does NOT reproduces issue on my pc.
To reproduce it, i need to increase array size to new int[50000][1000]

And here's what i get at profiler.

GC behavior without issue:

![screenshot from 2016-11-29 13-02-04](https://cloud.githubusercontent.com/assets/12250879/20705452/0e843d94-b634-11e6-80fe-2b332f233716.png)


GC behavior with issue:

![screenshot from 2016-11-29 13-02-46](https://cloud.githubusercontent.com/assets/12250879/20705478/24fabdfa-b634-11e6-8e23-379cc6a87ee3.png)

**Comment by raver119** [comment]
TL/DR: JVM spends x10 more time during garbage collection phase, if you spam it with tons of short-living objects.

**Comment by raver119** [comment]
Ah, and one more important thing: nd4j-native backend is also affected, as expected. Only because it's not a bug, it's basic JVM mechanic called "GC pause".

**Comment by raver119** [comment]
nd4j-native time without jvm spam:
```
o.d.o.l.PerformanceListener - iteration 281; iteration time: 35 ms; samples/sec: 1828.571; batches/sec: 28.571; 
o.d.o.l.PerformanceListener - iteration 301; iteration time: 32 ms; samples/sec: 2000.000; batches/sec: 31.250; 
o.d.o.l.PerformanceListener - iteration 321; iteration time: 35 ms; samples/sec: 1828.571; batches/sec: 28.571; 
o.d.o.l.PerformanceListener - iteration 341; iteration time: 35 ms; samples/sec: 1828.571; batches/sec: 28.571; 
o.d.o.l.PerformanceListener - iteration 361; iteration time: 31 ms; samples/sec: 2064.516; batches/sec: 32.258; 
o.d.o.l.PerformanceListener - iteration 381; iteration time: 32 ms; samples/sec: 2000.000; batches/sec: 31.250; 
```


nd4j-native with jvm spam:
```
o.d.o.l.PerformanceListener - iteration 121; iteration time: 250 ms; samples/sec: 256.000; batches/sec: 4.000; 
o.d.o.l.PerformanceListener - iteration 141; iteration time: 343 ms; samples/sec: 186.589; batches/sec: 2.915; 
o.d.o.l.PerformanceListener - iteration 161; iteration time: 200 ms; samples/sec: 320.000; batches/sec: 5.000; 
o.d.o.l.PerformanceListener - iteration 181; iteration time: 300 ms; samples/sec: 213.333; batches/sec: 3.333; 
o.d.o.l.PerformanceListener - iteration 201; iteration time: 234 ms; samples/sec: 273.504; batches/sec: 4.274; 
```

**Comment by treo** [comment]
@raver119 can you try this with several different GCs? like ConcMarkSweep, G1, ParallelGC?

**Comment by raver119** [comment]
I've did that. Results are pretty much equal.

**Comment by lpaatero** [comment]
I did continue to investigate my original issue in order to create work-around. As result I can reproduce the problem better now.

To create test case, I made following modification to org.deeplearning4j.examples.convolution.LenetMnistExample example:

```
public static void main(String[] args) throws Exception {
        int nChannels = 1; // Number of input channels
        int outputNum = 10; // The number of possible outcomes
        int batchSize = 64; // Test batch size
        int nEpochs = 1; // Number of training epochs
        int iterations = 1; // Number of training iterations
        int seed = 123; //

        **ArrayList<Object> d = new ArrayList<>();
        for (int ct=0; ct<2000000; ct++) {
            d.add(new byte[1000]);
        }**
    

```
So basically I make 2GB of allocation at the start of the program. Then I also set -Xmx10G to ensure there is sufficient memory.

As result from above changes, CUDA backend is really slow. Native backend is not impacted at all.
Both garbage collectors seem to produce about same result.

**Comment by raver119** [comment]
Yep. Now increase it a bit more, and you'll see native backend affected as
well. I've posted numbers for native backend earlier

30 нояб. 2016 г. 23:23 пользователь "Lauri Paatero" <
notifications@github.com> написал:

**Comment by lpaatero** [comment]
Please note that above change does NOT create any additional garbage at all. It allocates objects into heap before computation, and just lets the data sit there. So only garbage is what original LenetMnistExample itself generates.

I tested doubling data with native backend, and it is sill not affected. Right now I do not have time to post the numbers, I will do it as soon as I can.

**Comment by lpaatero** [comment]
#2416 seemed already gave numbers for native vs cuda. 
For CUDA I get 
```
o.d.o.l.PerformanceListener - iteration 1; iteration time: 21174 ms; samples/sec: 3.023; batches/sec: 0.047; 
o.d.o.l.PerformanceListener - iteration 2; iteration time: 4181 ms; samples/sec: 15.307; batches/sec: 0.239; 
o.d.o.l.PerformanceListener - iteration 3; iteration time: 6070 ms; samples/sec: 10.544; batches/sec: 0.165; 
o.d.o.l.PerformanceListener - iteration 4; iteration time: 26 ms; samples/sec: 2461.538; batches/sec: 38.462; 
o.d.o.l.PerformanceListener - iteration 5; iteration time: 7566 ms; samples/sec: 8.459; batches/sec: 0.132; 
o.d.o.l.PerformanceListener - iteration 6; iteration time: 24 ms; samples/sec: 2666.667; batches/sec: 41.667; 
o.d.o.l.PerformanceListener - iteration 7; iteration time: 4994 ms; samples/sec: 12.815; batches/sec: 0.200; 
o.d.o.l.PerformanceListener - iteration 8; iteration time: 20 ms; samples/sec: 3200.000; batches/sec: 50.000; 
o.d.o.l.PerformanceListener - iteration 9; iteration time: 3311 ms; samples/sec: 19.330; batches/sec: 0.302; 
```
And for native I get
```
o.d.o.l.PerformanceListener - iteration 1; iteration time: 182 ms; samples/sec: 351.648; batches/sec: 5.495; 
o.d.o.l.PerformanceListener - iteration 2; iteration time: 123 ms; samples/sec: 520.325; batches/sec: 8.130; 
o.d.o.l.PerformanceListener - iteration 3; iteration time: 124 ms; samples/sec: 516.129; batches/sec: 8.065; 
o.d.o.l.PerformanceListener - iteration 4; iteration time: 111 ms; samples/sec: 576.577; batches/sec: 9.009; 
o.d.o.l.PerformanceListener - iteration 5; iteration time: 114 ms; samples/sec: 561.404; batches/sec: 8.772; 
o.d.o.l.PerformanceListener - iteration 6; iteration time: 112 ms; samples/sec: 571.429; batches/sec: 8.929; 
o.d.o.l.PerformanceListener - iteration 7; iteration time: 102 ms; samples/sec: 627.451; batches/sec: 9.804; 
o.d.o.l.PerformanceListener - iteration 8; iteration time: 106 ms; samples/sec: 603.774; batches/sec: 9.434; 
o.d.o.l.PerformanceListener - iteration 9; iteration time: 109 ms; samples/sec: 587.156; batches/sec: 9.174; 

```
So native is not impacted, its performance is not a problem at all.

Even in CUDA case java GC does not seem to use much time, in above it was taking  ~10% of time:
![screenshot_20161201_204735](https://cloud.githubusercontent.com/assets/7058637/20807918/5f00e750-b809-11e6-900f-349cfcf45333.png)

Instead CUDA specific AtomicAllocator$UnifiedGarbageCollectorThread seems to be taking a lot of time:
![screenshot_20161201_205104](https://cloud.githubusercontent.com/assets/7058637/20808009/b4733e9a-b809-11e6-89a5-4dd969640fc9.png)

**Comment by raver119** [comment]
UnifiedGC threads is spending time in sleep() call, you can check that via cpu profiler (i mean not hot-spots entry). But AsyncIterator being topped - THAT IS interesting.

**Comment by raver119** [comment]
Also take a look here: https://github.com/deeplearning4j/deeplearning4j/issues/2416#issuecomment-264249423

It's something i'm working on in background right now. I have two hypothetical models that'll allow us to totally get rid of JVM GC reliance, and i hope in 0.8.0 we'll have one of them implemented.

**Comment by lpaatero** [comment]
OK.
It seems that with parameters I have, native backend is working perfectly fine, so I will use it as workaround.

**Comment by agibsonccc** [comment]
Closing in favor of #2477
