### ISSUE TITLE
Support for cuDNN 6.0

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#3143]
Release candidate is available for cuDNN 6.0. Downloads are available via http://blog.yannisassael.com/2017/02/cudnn-v6-0-rc/.

At surface level does not appear to be any breaking changes with existing code. @saudet would I need to recompile javacpp bindings or can I simply drop in the library files and give it a whirl?

Personally I'm wondering if this fixes issues like:
- https://github.com/deeplearning4j/deeplearning4j/issues/3091
- https://github.com/deeplearning4j/deeplearning4j/issues/3064

**Comment by saudet** [comment]
You could try to create a link to `libcudnn.so.5` and such and see what that gives, but I doubt that will work..

**Comment by agibsonccc** [comment]
@saudet fixed this

**Comment by saudet** [comment]
@crockpotveggies Let us know if this fixes the issues you've been having with cuDNN 5!

**Comment by crockpotveggies** [comment]
Unfortunate news, it looks like there's been API changes in cuDNN 6 that are affecting us. Our examples run fine since they're smaller convolutions, however they fail when trying to run larger models like Inception or AlexNet. I've reproduced this across multiple projects.

Do we have an NVIDIA dev who can give us some insight on what exactly was dropped?

**Comment by crockpotveggies** [comment]
@agibsonccc please reopen

**Comment by crockpotveggies** [comment]
So when using a convolutional model such as AlexNet or Inception that uses SAME padding and also configures padding >0 in convolutions, cuDNN 6 will return a CUDNN_STATUS_NOT_SUPPORTED.

It appears that when input images are > 1 channel, this error will be thrown. I'm not quite sure why, but that currently seems to be the only problem with support for cuDNN 6.

**Comment by crockpotveggies** [comment]
I've narrowed this to a potential "bug" or "feature" in cuDNN (depending on how you look at it).

It *looks* like `cudnnGetConvolutionForwardAlgorithm` eventually calls `cudnnGetConvolutionForwardWorkspaceSize` when selecting an algorithm for convolution. According to the user guide, a CUDNN_STATUS_NOT_SUPPORTED is thrown on this function when:

> The combination of the tensor descriptors, filter descriptor and convolution descriptor is not supported for the specified algorithm.

After browsing the User Guide, this can be the only explanation for why we're getting this specific error on `cudnnGetConvolutionForwardAlgorithm`, even though the docs itself say this function does not throw an UNSUPPORTED error.

**Comment by crockpotveggies** [comment]
Are we happy with adding a new ENUM to `ConvolutionLayer.AlgoMode.` such as `.cudnnAlgoMode(ConvolutionLayer.AlgoMode.USER_SPECIFIED)`? This will allow the user to choose from specific algorithms such as:

- `CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_GEMM`
- `CUDNN_CONVOLUTION_FWD_ALGO_GEMM`
- `CUDNN_CONVOLUTION_FWD_ALGO_FFT`
- `CUDNN_CONVOLUTION_FWD_ALGO_FFT_TILING`

There may be other parameters here which we may have to calculate ourselves, such as workspace size, etc.

**Comment by saudet** [comment]
@crockpotveggies If it's actually useful, we can map more of cuDNN sure!

**Comment by crockpotveggies** [comment]
After some very extensive testing over the last 12 hours, I think I can
rule out the specific algorithm being the cause here. I'm leaning to either
a misuse of a cudnn API or a bug. @saudet I did notice all of the algorithm
codes were mapped already, so we can probably hold off on that :)

On Wed, Apr 5, 2017 at 9:18 PM Samuel Audet <notifications@github.com>
wrote:

@crockpotveggies <https://github.com/crockpotveggies> If it's actually
useful, we can map more of cuDNN sure!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/deeplearning4j/deeplearning4j/issues/3143#issuecomment-292053645>,
or mute the thread

**Comment by crockpotveggies** [comment]
Good news is I've correctly identified the cause of this bug. The padding we're passing to cuDNN is not what it expects. For example, take the following convolution layer from the stem of FaceNet:

```
new ConvolutionLayer.Builder(new int[]{7,7}, new int[]{2,2}).nIn(3).nOut(64).convolutionMode(ConvolutionMode.Same).build())
```

Using SAME mode, the output padding is `2,2`. However, cuDNN (for reasons not yet understood) doesn't like this. Changing this layer to the following gets rid of the CUDNN_STATUS_NOT_SUPPORTED error:

```
new ConvolutionLayer.Builder(new int[]{7,7}, new int[]{2,2}, new int[]{3,3}).nIn(3).nOut(64).convolutionMode(ConvolutionMode.Truncate).build())
```

After adding similar configurations throughout the FaceNetVariant model, cuDNN no longer throws an error.

The next question is, where is the problem originating? When I contacted Brandon Amos about his FaceNet model he was specific in saying that FaceNet used SAME padding. So are we generating incorrect padding values? Did cuDNN add some checks since v5.1? Is this simple user error of constructing a proper model? Should we be handling this automatically for our users like how other frameworks do?

**Comment by crockpotveggies** [comment]
@AlexDBlack see above

**Comment by saudet** [comment]
BTW, Alex did add some code that changes the padding used by cuDNN when convolutionMode == ConvolutionMode.Same:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-cuda/src/main/java/org/deeplearning4j/nn/layers/convolution/CudnnConvolutionHelper.java#L199
What was the rationale behind that?

**Comment by crockpotveggies** [comment]
Interesting, I noticed that too. Isn't that being called twice since that code also exists in ConvolutionLayer? Next step is to check if it works without it.

**Comment by saudet** [comment]
I'm not able to reproduce that `CUDNN_STATUS_NOT_SUPPORTED` with `ConvolutionMode.SAME` and padding > 0. Could you provide some sample code for that? Thanks!

**Comment by saudet** [comment]
I think I was able to squash the bug. Let me know if the above works with everything! Thanks for testing

**Comment by saudet** [comment]
@agibsonccc @AlexDBlack How do you think we should expose parameters specific to cuDNN? As normal layer parameters as per https://github.com/deeplearning4j/deeplearning4j/issues/3143#issuecomment-291962994?

**Comment by AlexDBlack** [comment]
@saudet yeah, I think standard enums for the cudnn-specific params is the way to go. It's not ideal (being not applicable to anyone not using cudnn) but I don't think there's any other real option here.
The only other thing I can think of is have the config on say MultiLayerConfiguration (instead of separately per layer) - but then one day, some user will probably say "I want to configure them separately for different layers" which we won't be able to do.

**Comment by crockpotveggies** [comment]
@saudet appears fixed but still need to test it a bit. Might have exposed a problem in auto-calculation of params in MLN.

**Comment by aditbhrgv** [comment]
I am facing this issue on CUDNN 6.0 and CUDA 8.0
How was it fixed ?

**Comment by AlexDBlack** [comment]
@aditbhrgv Please don't post on 7 month old closed issues.
Make sure you are up to date with DL4J - 0.9.1 version, have cuda+cudnn installed properly, and if that doesn't work, ask again here with more details: https://gitter.im/deeplearning4j/deeplearning4j
