### ISSUE TITLE
PW + AsyncIterator leaks memory

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#3234]
#### Issue Description

After 7 epochs using Inception on a long-running training process, AsyncIterator will leak memory and eventually throw this exception:

```
[AsyncIterator thread] ERROR java.lang.Throwable - Exception in thread "AsyncIterator thread" java.lang.OutOfMemoryError: Cannot allocate new FloatPointer(8644): totalBytes = -439058375, physicalBytes = 57G
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:76)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:41)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.set(BaseCudaDataBuffer.java:429)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:115)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:102)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createFloat(CudaDataBufferFactory.java:171)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1212)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:393)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:636)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.nd4j.linalg.jcublas.JCublasNDArray.<init>(JCublasNDArray.java:297)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:332)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1375)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3415)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.nd4j.linalg.util.NDArrayUtil.toNDArray(NDArrayUtil.java:35)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.nd4j.linalg.util.FeatureUtil.toOutcomeVector(FeatureUtil.java:39)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.getDataSet(RecordReaderDataSetIterator.java:256)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:199)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:411)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:53)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$IteratorRunnable.run(AsyncDataSetIterator.java:364)
[AsyncIterator thread] ERROR java.lang.Throwable - Caused by: java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes = 57G > maxPhysicalBytes = 56G
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:572)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.bytedeco.javacpp.Pointer.init(Pointer.java:121)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.bytedeco.javacpp.FloatPointer.allocateArray(Native Method)
[AsyncIterator thread] ERROR java.lang.Throwable - 	at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:68)
[AsyncIterator thread] ERROR java.lang.Throwable - 	... 19 more
[Thread-71] ERROR org.deeplearning4j.parallelism.ParallelWrapper - Uncaught exception: java.lang.OutOfMemoryError: Cannot allocate new FloatPointer(1): totalBytes = -439058623, physicalBytes = 56G
```

Unsure how to address it. With new workspace I have GC disabled, and I'm unsure if GC can solve this problem.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j MASTER
* ubuntu 16.04
* CUDA 8, cuDNN 6
* NVIDIA driver 378

**Comment by raver119** [comment]
Where can i see the code, which reproduces this behavior?

**Comment by raver119** [comment]
And what happens with periodic GC enabled?

**Comment by raver119** [comment]
And why do you think it's ADSI leaking? Not sure too...

**Comment by crockpotveggies** [comment]
FYI ran into this again on your branch:

```
[main] INFO RCROPSTAGE1-0.1LR-72BATCH - *** Completed epoch 8, time: 845588 ***
[main] ERROR java.lang.Throwable - Exception in thread "main" java.lang.OutOfMemoryError: Cannot allocate new BytePointer(33631): totalBytes = -439058631, physicalBytes = 28G
[main] ERROR java.lang.Throwable - 	at org.bytedeco.javacpp.BytePointer.<init>(BytePointer.java:103)
[main] ERROR java.lang.Throwable - 	at org.bytedeco.javacpp.BytePointer.<init>(BytePointer.java:68)
[main] ERROR java.lang.Throwable - 	at org.bytedeco.javacpp.opencv_core$Mat.<init>(opencv_core.java:14907)
[main] ERROR java.lang.Throwable - 	at org.bytedeco.javacpp.opencv_core$Mat.<init>(opencv_core.java:14906)
[main] ERROR java.lang.Throwable - 	at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:194)
[main] ERROR java.lang.Throwable - 	at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:187)
[main] ERROR java.lang.Throwable - 	at org.datavec.image.recordreader.BaseImageRecordReader.next(BaseImageRecordReader.java:216)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:198)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:411)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:53)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.nn.graph.ComputationGraph.doEvaluation(ComputationGraph.java:2634)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.nn.graph.ComputationGraph.evaluate(ComputationGraph.java:2516)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.nn.graph.ComputationGraph.evaluate(ComputationGraph.java:2490)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.nn.graph.ComputationGraph.evaluate(ComputationGraph.java:2469)
[main] ERROR java.lang.Throwable - 	at ai.bernie.train.TrainClassifier.run(TrainClassifier.java:207)
[main] ERROR java.lang.Throwable - 	at ai.bernie.train.TrainerRunner.run(TrainerRunner.java:141)
[main] ERROR java.lang.Throwable - 	at ai.bernie.train.TrainerRunner.main(TrainerRunner.java:163)
[main] ERROR java.lang.Throwable - Caused by: java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes = 28G > maxPhysicalBytes = 28G
[main] ERROR java.lang.Throwable - 	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:572)
[main] ERROR java.lang.Throwable - 	at org.bytedeco.javacpp.Pointer.init(Pointer.java:121)
[main] ERROR java.lang.Throwable - 	at org.bytedeco.javacpp.BytePointer.allocateArray(Native Method)
[main] ERROR java.lang.Throwable - 	at org.bytedeco.javacpp.BytePointer.<init>(BytePointer.java:95)
[main] ERROR java.lang.Throwable - 	... 16 more
```

**Comment by raver119** [comment]
Issue is fixed, ParallelWrapper wasn't reusing MQ instance, so after each epoch new MQ was instantiated.
