### ISSUE TITLE
CUDA error while training a CNN

### ISSUE THREAD

**Issue by Saminobi** [deeplearning4j/deeplearning4j#3582]
#### Issue Description

While training a CNN on time series data and testing different kernel size/stride values, the training started getting slow until it finally stopped giving the following error:
https://gist.github.com/Saminobi/de120057afa7198dfb0c827d89e17b6b

The CNN configuration at the time of the error was:
https://gist.github.com/Saminobi/7f58482ebdcb35d2be625aa4d4fade68

The network is a test, it is not meant to classify properly but to measure the impact that kernel size/stride/feature maps depth/number of layers values have in the time needed for training.

The number of epochs are 100, with 6 iterations each, where the batch size for each iteration is 1000. It stopped the training on the 21st epoch, on the 5th iteration.
I'm using learning rate schedule but the training stopped before the value changed from the initial one (0.01). It might be irrelevant but the training is using the AsyncDataSetIterator.

CudaEnviroment settings: https://gist.github.com/Saminobi/b7c1a55f4e4d31faa7d56641ab424613
nd4j/dl4j/datavec versions: https://gist.github.com/Saminobi/a2b1b4c2c1c75ff7d2f1aab8c94de68d

#### Version Information

* Deeplearning4j version = 0.8 (is not built locally)
* Windows 7
* CUDA version 8.0.61
* NVIDIA driver 382.53
* GeForce GTX 1080Ti

**Comment by saudet** [comment]
IIRC, there are a few bugs that were fixed w.r.t to strides since 0.8.0. It might work properly with 0.8.1-SNAPSHOT, have you tried?

**Comment by AlexDBlack** [comment]
I'm unable to reproduce this (with 10k iterations of minibatch size 1k) with cudnn 8 + DL4J 0.8.0 (Windows 10), Titan X (Pascal).
I tried with/without the cuda configuration provided. The configuration (though small) look OK/valid.

Note that your maxPool method isn't provided in the gist; I assumed ```maxPool("maxpool1", new int[]{1, 11}, new int[]{1, 20})``` was kernel [1,11], stride [1,20]

**Comment by raver119** [comment]
what cudnn version was used? 5.1 or 6.0?

**Comment by AlexDBlack** [comment]
CUDNN 6 for me.

@Saminobi for snapshots: https://github.com/deeplearning4j/deeplearning4j/issues/3227

**Comment by Saminobi** [comment]
@saudet @AlexDBlack after posting in gitter @raver119 told me also to change to 0.8.1-SNAPSHOT so I will use those versions from now on. My cudNN version is 6. And I apparently forgot to include it but yes, my maxPool method looks like the one posted here.
Since it is not reproducible, I will use the newer versions and I will open another issue if I get again the error. Thanks for the snapshots' link.

**Comment by raver119** [comment]
Thanks.  Keep us posted please.

**Comment by Saminobi** [comment]
A new error came up (as posted in gist as well).  I left my cnn to train at night on different kernel size/stride values. In the logs I keep, it started slowing down gradually from kernelSize = 7, stride = 1, up to kernelSize = 19, stride = 18 where it gave this error (full log output):
https://gist.github.com/Saminobi/90d244738e321a7928ff24c6e77c7e97

My cnn configuration at the time of the error was: https://gist.github.com/Saminobi/8aeac536a2b9cb183339d6ddaa15d567

**Comment by raver119** [comment]
As said before - please use 0.8.1-SNAPSHOT.

**Comment by Saminobi** [comment]
Once I tried to run another training with the 0.8.1-SNAPSHOT versions it gave me the following compiling errors:
```
C:\Users\user\IdeaProjects\dl4j-examples\dl4j-examples\src\main\java\org\deeplearning4j\examples\recurrent\encdec\CorpusIterator.java
Error:(17, 8) java: org.deeplearning4j.examples.recurrent.encdec.CorpusIterator is not abstract and does not override abstract method getPreProcessor() in org.nd4j.linalg.dataset.api.iterator.MultiDataSetIterator

C:\Users\users\IdeaProjects\dl4j-examples\dl4j-examples\src\main\java\org\deeplearning4j\examples\recurrent\seq2seq\CustomSequenceIterator.java
Error:(26, 8) java: org.deeplearning4j.examples.recurrent.seq2seq.CustomSequenceIterator is not abstract and does not override abstract method getPreProcessor() in org.nd4j.linalg.dataset.api.iterator.MultiDataSetIterator
```
The problem must be in my pom file as I'm not sure if I placed the `<repositories>` correctly, as mentioned in #3227 

Here is my pom file of the parent folder: https://gist.github.com/Saminobi/ed99e7d3c47bc81c599f16783521a05c

**Comment by raver119** [comment]
That's expected. You're using our examples, which are set to use 0.8.0, and there's quite enough changes in 0.8.1-SNAPSHOT.

Just implement those missing methods, i.e. `return null` and go on :)

**Comment by Saminobi** [comment]
When I tried the 0.8.1-SNAPSHOT versions I was getting some cudNN warnings that it couldn't find jnicudnn.dll. For some reason it was still looking on the cache of `javacpp-presets` version `8.0-1.3` instead of `8.0-6.0-1.3`. I solved it by cloning the repository again. Now the training worked and I implemented also the Workspaces feature. For every new kernel size/stride/nOut values (new set of training for every new set of values) I kept destroying the previous workspace and I created a new one before the main epoch loop with the `model.fit(data)` (garbage collector is disabled). 
I left it yesterday evening to train and unfortunately, it trained only for an hour before giving me the following error: https://gist.github.com/Saminobi/da8d74e8642e2618d4927a6ee20f2580

The `DEVICE[0]` is my GPU? And if yes, could the problem be that I set the memory cache to 5GB in `CudaEnvironment`?

Number of epochs, dataset size and batchsize value are all the same. Here is the cnn configuration when it crushed:https://gist.github.com/Saminobi/d1e305525f2751664f55d23763a30a70

**Comment by raver119** [comment]
Sorry, what exactly you did with workspaces?

**Comment by Saminobi** [comment]
I added the `.trainingWorkspaceMode(WorkspaceMode.SINGLE)` and `.inferenceWorkspaceMode(WorkspaceMode.SINGLE)` in the cnn configuration, `Nd4j.getMemoryManager().togglePeriodicGc(false);` right before the main for loop which contains the `model.fit(data)` and `Nd4j.getWorkspaceManager().destroyAllWorkspacesForCurrentThread();` after the evaluation of 100 epochs (a whole training with a specific set of kernel size/stride/nOut values) has taken place.

**Comment by raver119** [comment]
> Nd4j.getWorkspaceManager().destroyAllWorkspacesForCurrentThread();

Do not call this. We have one strange issue which i can't fix yet, you might be hitting it.

**Comment by raver119** [comment]
https://github.com/deeplearning4j/nd4j/issues/1865

**Comment by Saminobi** [comment]
> Do not call this. We have one strange issue which i can't fix yet, you might be hitting it.

Ok, thanks for letting me know, I wasn't aware of it. I will enable GC then with `Nd4j.getMemoryManager().setAutoGcWindow(5000)` and I will stop calling `Nd4j.getWorkspaceManager().destroyAllWorkspacesForCurrentThread();`.

**Comment by raver119** [comment]
disabled gc is ok.

It's probably just memory fragmentation issue...

**Comment by Saminobi** [comment]
I see, thanks.

**Comment by Saminobi** [comment]
I left it train for the weekend and it didn't give me any errors. Thanks for the help!

**Comment by raver119** [comment]
Perfect. Thanks for letting us know.
