### ISSUE TITLE
Error while importing the .hdf5 file of an SSD net from Keras 1.2.2

### ISSUE THREAD

**Issue by StefanoSamele** [deeplearning4j/deeplearning4j#3883]
We are working on the import of an SSD net from Keras (v 1.2.2). We separately import the .json file (which contains the model) and the .hdf5 file (which contains the weights). We are facing some problem with the import of .hdf5 file: https://gist.github.com/StefanoSamele/0af90b55845c1ab76a26d26414823ffc.
 
Furthermore at line 614 of the gist there is a CUDA error we are not sure about the nature of.

* Deeplearning4j version: 0.9.2-SNAPSHOT
* CUDA version: nd4j-cuda-8.0-platform

**Comment by maxpumperla** [comment]
@StefanoSamele will look into this after the weekend. Can you share the `hdf5` file? Otherwise it will be difficult to investigate. Also, do you use tensorflow or theano? Which OS do you use?

**Comment by StefanoSamele** [comment]
We use the tensorflow backend.
Here is the .hdf5 file(weights_SSD300.hdf5): https://mega.nz/#F!7RowVLCL!q3cEVRK9jyOSB9el3SssIA. Thank you

**Comment by maxpumperla** [comment]
thanks! one other follow up question: are you using `bias = false` somewhere? We recently noticed that excluding bias terms e.g. in conv layers will screw up the import due to mismatching weights.

If it's not too much trouble, could you please also send the model json? It's quicker to inspect what's going on.

**Comment by StefanoSamele** [comment]
About the bias = false setting I could check (my guess is that we are not using bias = false), but I forgot to mention that the import was working correctly with 0.9.1 version of DL4J. 
We have also slightly manually modified the .json file: https://gist.github.com/StefanoSamele/2e966b862f452e45e94b91b204c55289

**Comment by maxpumperla** [comment]
@StefanoSamele cool, thanks. it's _really_ good to know it did work before (we had a TF "fix" earlier), I'm now 95% sure I know what causes the issue. Will try to fix it tomorrow.

**Comment by maxpumperla** [comment]
OK, when I run your stuff like this:
```
        ClassLoader classLoader = getClass().getClassLoader();
        File kerasFile = new File(classLoader.getResource("weights_SSD300.hdf5").getFile());
        File kerasModel = new File(classLoader.getResource("ssd_model.json").getFile());

        org.deeplearning4j.nn.api.Model importedModel =
                        KerasModelImport.importKerasModelAndWeights(kerasModel.getAbsolutePath(), kerasFile.getAbsolutePath());
```

it throws:
```
org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type AtrousConvolution2D.
```
at me. We do not support Atrous conv layers atm.

**Comment by maxpumperla** [comment]
If you say it worked before, could you please tell me if the import still worked at this SHA:
e5cd5e54bf2cbbc7d51b5187ba13400ea670ab38
? (If at all, it should be working then).

**Comment by StefanoSamele** [comment]
So far we have implemented all the custom layers we need in order to import the net (not only the atrous but also a bunch of others such as the KerasReshape layer).
Not sure about the SHA you are talking about; I can see we are using the following import: org.nd4j.linalg.primitives.Pair wherever is needed, also in our custom layers. 
Since it's a commit made for version 0.9.1, I can confirm you that the import is working at that SHA (just re- tested), if I understood correctly your observation.
P.S. It's not strictly connected to this issue but I am still trying the import of the net in the 0.9.2-SNAPSHOT version and I think now it's making conflict with the new version of the KerasReshape layer (#3876).

**Comment by maxpumperla** [comment]
hmm, I'm a little at a loss how I'm supposed to help you here, unless you either strip your example of unsupported layers or _share_ your new layers with us (why not create a PR?). At the very least you have to tell me how our new Reshape layer impl differs from yours and what seems to be the problem.

I was pointing you to that SHA as this was the last commit before https://github.com/deeplearning4j/deeplearning4j/pull/3860, which I think is causing your problems. I thought I resolved it after (see https://github.com/deeplearning4j/deeplearning4j/pull/3862), but it does not seem to be the case then.

**Comment by StefanoSamele** [comment]
We would like to share with you our work; we are talking with @AlexDBlack to share with you all the new layers (our understanding it's that he's working like us on the SSD net), but my team and I need some time to review the work done.
I am investigating the problem with the KerasReshape layer. I can definitely pm you about this if you are interested, as soon as I find out something, so that we can keep this space clean.
Still we were wondering why the import of the .hdf5 file is working with the 0.9.1, while with 0.9.2-SNAPSHOT it's giving this error...

**Comment by maxpumperla** [comment]
Yes, let's please keep in touch about this. On my side, regarding the import error in general, I can try to provide you with a branch that I think will work, but I can't test anything on my end...

**Comment by lucaruzzola** [comment]
Hi, while @StefanoSamele is away this week, I'll be looking into this. 
Before sharing the layers we'd like to do some code review and setup the project nicely.
@maxpumperla if you could please provide us with the branch, we're open to testing it, thanks for the support!

**Comment by AlexDBlack** [comment]
@lucaruzzola I'm happy to do code review for new layers/vertices for SSD, feel free to direct message me on gitter.

**Comment by maxpumperla** [comment]
@lucaruzzola we just merged a large PR for keras 2 support. It also has a lot more unit tests. Maybe your model import will also work again. (As I don't really know what you're doing, I can't tell. At least it's worth a try.)

**Comment by lucaruzzola** [comment]
Thanks, we'll give it a try!

**Comment by lucaruzzola** [comment]
@maxpumperla We tried again, it still throws the same error(s)

**Comment by lucaruzzola** [comment]
We're now no longer seeing the hdf5 issue, but experiencing https://gist.github.com/lucaruzzola/e92624f542856b4b87c341d4c4170f28

**Comment by maxpumperla** [comment]
can we create a new ticket please and close this one? fwiw this error sometimes happens on my side as well, but rarely.

**Comment by lucaruzzola** [comment]
I guess so, i'll open a new issue and maybe reference this one

**Comment by maxpumperla** [comment]
closing this one, as discussed
