### ISSUE TITLE
DL4J | NLP: java.lang.OutOfMemoryError when running an NLP example on both CPU and GPU versions

### ISSUE THREAD

**Issue by neomatrix369** [deeplearning4j/deeplearning4j#8306]
#### Issue Description

Please describe our issue, along with:
- expected behavior

Training finishes without complaining about "too" much memory used on machines with different resources (8GB upwards) for both CPU and GPU types of the app.

- encountered behavior

The [pom.xml](https://gist.github.com/neomatrix369/0ed60326cedbf4938b6c2b13bf46554f) for the project. This is a modified version from the original examples at https://github.com/deeplearning4j/dl4j-examples (see folder with `org/deeplearning4j/examples/convolution/sentenceclassification/CnnSentenceClassificationExample`)

### CPU version

I get this error "java.lang.OutOfMemoryError: Cannot allocate new BytePointer(1200): totalBytes = 2921M, physicalBytes = 6717M" when I run the java app. See [logs](https://gist.github.com/neomatrix369/f444933bffbf4ec5481f9d61e85cd04f) for the CPU version.

### GPU version

I get this error "Exception in thread "main" java.lang.OutOfMemoryError: Cannot allocate new FloatPointer(300): totalBytes = 2194M, physicalBytes = 7013M" when I run the java app. See [logs](https://gist.github.com/neomatrix369/8125f18f2a1d6da236ab5bd26831e69d) for the GPU version.

### Linux Machine spec

- Linux 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- 16 GB RAM
-  NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] (rev a1)

### MacOSX Machine spec

- MacOSX 10.13.6 (High Sierra)
- 16 GB RAM 
- No CUDA

### Run command

```
time java -Djava.library.path=""                 \
     -jar ${TARGET_JAR_FILE}                     \
     -Xmx8g                                      \
     -Dorg.bytedeco.javacpp.maxbytes=10G         \
     -Dorg.bytedeco.javacpp.maxphysicalbytes=10G \
     $*%
```

Training is interrupted on machines even with 16GB or higher RAM, although seems to work fine on machines with high-spec. This is especially true when running in GPU mode. Although I have had this happen for CPU versions of the app.

Although I have had it work on my MacOS in CPU mode without a complain a few times (it did fail later on).

I did check quickly https://github.com/eclipse/deeplearning4j/issues/8236 and https://github.com/eclipse/deeplearning4j/issues/4918 and they seem to be different but maybe I'm missing some details.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: `1.0.0-beta4`
* Platform information (OS, etc): `Linux and MacOS`
* CUDA version, if used: `10.1.243`
* NVIDIA driver version, if in use: 
```
   Driver Version: 418.87.01
   NVRM version: NVIDIA UNIX x86_64 Kernel Module  418.87.01  Wed Sep 25 06:00:38 UTC 2019
   GCC version:  gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 
```
Please let me know if the above details are not sufficient and you need more.

**Comment by raver119** [comment]
> Deeplearning4j version: 1.0.0-beta

Are you sure about version?

**Comment by neomatrix369** [comment]
> > Deeplearning4j version: 1.0.0-beta
> 
> Are you sure about version?

It's `1.0.0-beta4` - sorry about that just updated it!

Also updated the details with GPU and machine related specs. Please let me know if you need anything else.

**Comment by neomatrix369** [comment]
Additional question I noticed the below on the Readme page of the repo:

```
./change-cuda-versions.sh x.x
./change-scala-versions.sh 2.xx
./change-spark-versions.sh x
mvn clean install -Dmaven.test.skip -Dlibnd4j.cuda=x.x -Dlibnd4j.compute=xx
```

and

```
mvn -B -V -U clean install -pl '!jumpy,!pydatavec,!pydl4j' -Dlibnd4j.platform=linux-x86_64 -Dlibnd4j.chip=cuda -Dlibnd4j.cuda=9.2 -Dlibnd4j.compute=<your GPU CC> -Djavacpp.platform=linux-x86_64 -Dmaven.test.skip=true
```
( i do understand that the above might be specific to building this project, so I should pick and choose whichever applies to me )

Is this the recommended way we should build our Java/JVM apps? Can you please point me to the docs where all the properties and JVM flags are enlisted (that can be passed as CLI args to maven or gradle or even at runtime of the app).

**Comment by raver119** [comment]
I see. Please update to 1.0.0-beta5.

**Comment by treo** [comment]
@neomatrix369 also, to reduce some confusion: the instructions that you see there are to build dl4j and all supporting libraries from source. You do not have to do that, unless you are actively working on the actual dl4j source code. All you have to do is update your version number.

**Comment by neomatrix369** [comment]
Thanks @raver119 this has resolved the OOEM complains. Also good improvements elsewhere with notifying and checking various things that can go wrong.

Although I get this warning message at the start of the run:

```
18:05:41 2019-10-22 17:05:41,853ate - 17:05:41,853 WARN ~ *** ND4J VERSION CHECK FAILED - INCOMPATIBLE VERSIONS FOUND ***
18:05:41 2019-10-22 17:05:41,853ate - 17:05:41,853 WARN ~ Incompatible versions (different version number) of DL4J, ND4J, RL4J, DataVec, Arbiter are unlikely to function correctly
...
```

It continues to run without an issue but it's not clear from the message:
- what it is checking that it found was incorrect?
- what it did to fix it or overcome it?

I would help to supply these are log messages, that way we know if the warning means if it is still needing to be fixed or it has been fixed subsequently.

@treo Thanks for that, I'll take a note of it.
